CREATE TABLE "GCG_4229_OPEN_PYMNTS"(
 "BIRUNID" BIGINT NOT NULL ,
 "VENDOR" CHAR(7),
 "NAME_VENDOR_PAY" CHAR(30),
 "INVOICE" CHAR(15),
 "BATCH_CODE" CHAR(2),
 "BATCH_NUM" CHAR(5),
 "DATE_INVOICE_DUE" DATE,
 "DATE_INVOICE_DUE_J" DOUBLE,
 "DISCOUNT_INVOICE" DOUBLE,
 "EXCHANGE_CURR" CHAR(3),
 "EXCHANGE_RATE" DOUBLE,
 "EXCHANGE_AMT" DOUBLE,
 "VOUCHER" CHAR(7),
 "AMT_TRANSACTION" DOUBLE,
 "FLAG_PAY_SELECT" CHAR(1),
 "JOB" CHAR(7),
 "AMT_INVOICE" DOUBLE);

CREATE INDEX "IND0" USING 0 ON "GCG_4229_OPEN_PYMNTS"("BIRUNID", "VENDOR");